on:
  push:
    paths:
      - 'config/**'
  workflow_dispatch:

name: Build

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-build-arm:2.5
    name: Build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache west modules
        uses: actions/cache@v2
        env:
          cache-name: cache-zephyr-modules
        with:
          path: |
            modules/
            tools/
            zephyr/
            bootloader/
            zmk/
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('manifest-dir/west.yml') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: West Init
        run: west init -l config
      - name: West Update
        run: west update
      - name: West Zephyr export
        run: west zephyr-export

      - name: West Build (Enlil36 Left)
        run: west build -p -s zmk/app -b nice_nano -- -DSHIELD=enlil36_left -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Enlil36 DTS File
        if: ${{ always() }}
        run: cat -n enlil36_left/zephyr/enlil36_left.dts.pre.tmp
      - name: Enlil36 Left Kconfig file
        run: cat enlil36_left/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp enlil36_left/zephyr/zmk.uf2 enlil36_left.uf2
      - name: Archive (Enlil36 Left)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: enlil36_left.uf2

      - name: West Build (Enlil36 Right)
        run: west build -p -s zmk/app -b nice_nano -- -DSHIELD=enlil36_right -- -DZMK_CONFIG="${GITHUB_WORKSPACE}/config"
      - name: Enlil36 DTS File
        if: ${{ always() }}
        run: cat -n enlil36_right/zephyr/enlil36_right.dts.pre.tmp
      - name: Enlil36 Right Kconfig file
        run: cat enlil36_right/zephyr/.config | grep -v "^#" | grep -v "^$"
      - name: Rename zmk.uf2
        run: cp enlil36_right/zephyr/zmk.uf2 enlil36_right.uf2
      - name: Archive (Enlil36 Right)
        uses: actions/upload-artifact@v2
        with:
          name: firmware
          path: enlil36_right.uf2
